repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

      - id: check-added-large-files
        args:
          - --maxkb=500
      - id: check-symlinks
      - id: detect-private-key
  - repo: git@github.com:ConsultingMD/image-builder.git
    rev: 695c3a678c76d3c7b707a2c93a8fd64004574a65
    hooks:
      - id: go-mod-tidy
        description: ensure go mod tidy has been run after updates
      - id: generate-run
        description: ensure code generation runs successfully
      - id: generated-rm
        description: remove generated files from git index and ignore them
      - id: go-lint
      - id: golines
      # - id: terraform-fmt
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.2.211
    hooks:
      - id: checkov
        types:
          - dockerfile
          - terraform
        args:
          - --framework
          - circleci_pipelines
          - dockerfile
          - terraform
          - --quiet
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.0
    hooks:
      - id: prettier
        types_or:
          - javascript
          - jsx
          - json
          - ts
          - tsx
          - css
          - scss
          - less
          - html
          - json
          - graphql
          - markdown
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
